spring:
  cloud:
#     gateway:
#       routes:
#         - id: customer_srevice
#           uri: http://localhost:8081
#           predicates:
#             - Path=/customers/**

#           filters:
#             - PrefixPath=/api

#         - id: account_srevice
#           uri: http://localhost:8082
#           predicates:
#             - Path=/banck-accounts/**

#       # globalcors:
#       #   cors-configurations:
#       #     '[/**]':
#       #       allowedOrigins: "*"
#       #       allowedMethods:
#       #         - GET
#       #         - POST
#       #         - DELETE
#       #         - PUT
#       #         - OPTIONS
#       #         - HEAD
    # discovery:
    #   enabled: false

    config:
      enabled: false

#   application:
#     name: gateway-service


server:
  port: 8888

# # logging:
# #   level:
# #     org.springframework.cloud.gateway: DEBUG


spring